// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://bhkqdxhyceflfesxrztm.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJoa3FkeGh5Y2VmbGZlc3hyenRtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTU2ODQ3OTEsImV4cCI6MjA3MTI2MDc5MX0.JmUM-TE9VJ9nA9W2hkmYe1LxvMsJR9REAw4r49UZNFA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});